IMAGE:
  WIDTH: 640
  HEIGHT: 480
  ROI_START_HEIGHT: 360
  ROI_HEIGHT: 30 # 기존 30

CAR:
  START_SPEED: 254
  MAX_SPEED: 254
  MIN_SPEED: 254
  US_MAX_SPEED: 130
  US_MIN_SPEED: 100
  SPEED_CONTROL_THRESHOLD: 5.0
  ACCELERATION_STEP: 1
  DECELERATION_STEP: 1
  STOP: 0

PID:
  P_GAIN: 0.4
  I_GAIN: 0.0001
  D_GAIN: 0.025


MOVING_AVERAGE_FILTER: 30

CANNY:
  LOW_THRESHOLD: 180
  HIGH_THRESHOLD: 310

HOUGH:
  ABS_SLOPE_RANGE: 15
  THRESHOLD: 30
  MIN_LINE_LENGTH: 30
  MIN_LINE_GAP: 10


DEBUG: True